ref
<a>https://wikidocs.net/32829</a>

In [2]:
import numpy as np

In [3]:
vec = np.array([1, 2, 3, 4, 5])
print(vec)

[1 2 3 4 5]


In [4]:
mat = np.array([[10, 20, 30], [60, 70, 80]])
print(mat)

[[10 20 30]
 [60 70 80]]


In [5]:
print('vec의 타입 : ', type(vec))
print('mat의 타입 : ', type(mat))

vec의 타입 :  <class 'numpy.ndarray'>
mat의 타입 :  <class 'numpy.ndarray'>


In [6]:
print('vec의 축의 개수 :',vec.ndim)
print('vec의 크기(shape) : ', vec.shape)

vec의 축의 개수 : 1
vec의 크기(shape) :  (5,)


In [7]:
print('mat의 축의 개수 :',mat.ndim)
print('mat의 크기(shape) :',mat.shape)

mat의 축의 개수 : 2
mat의 크기(shape) : (2, 3)


In [8]:
zero_mat = np.zeros((2, 3))
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
one_mat = np.ones((2, 3))
print(one_mat)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
same_value_mat = np.full((2, 2), 9)
print(same_value_mat)

[[9 9]
 [9 9]]


In [12]:
eye_mat = np.eye(3)
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
random_mat = np.random.random((2,3))
print(random_mat)

[[0.40516919 0.16503582 0.24803662]
 [0.6244659  0.18618235 0.26081337]]


In [17]:
range_vec = np.arange(10)
print(range_vec)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
n=2
range_n_step_vec = np.arange(1, 10, n)
print(range_n_step_vec)

[1 3 5 7 9]


In [21]:
reshape_mat = np.array(np.arange(30)).reshape((5, 6))
print(reshape_mat)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


- Numpy 슬라이싱

In [22]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [28]:
slicing_mat = mat[0, :]
print(slicing_mat)

[1 2 3]


In [29]:
slicing_mat = mat[:, 1]
print(slicing_mat)

[2 5]


- Numpy 정수 인덱싱 (integer indexing)

In [30]:
mat = np.array([[1, 2], [4, 5], [7, 8]])
print(mat)

[[1 2]
 [4 5]
 [7 8]]


In [31]:
print(mat[1, 0])

4


In [32]:
indexing_mat = mat[[2, 1], [0, 1]]
print(indexing_mat)

[7 5]


- Numpy 연산

In [33]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])


In [34]:
# result = np.add(x, y)와 동일.
result = x + y
print(result)

[5 7 9]


In [35]:
# result = np.subtract(x, y)와 동일
result = x - y
print(result)

[-3 -3 -3]


In [37]:
# result = np.multiply(result, x) 와 동일
result = result * x
print(result)

[ -3 -12 -27]


In [38]:
# result = np.divide(result, x)와 동일
result = result / x
print(result)

[-3. -6. -9.]


In [39]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
mat3 = np.dot(mat1, mat2)
print(mat3)

[[19 22]
 [43 50]]
